add helpers for commonly used node searches
remerge/cookbook-base pull request #3
Opened 2019-01-21 16:10 UTC by asusac

2019-01-21 16:28 UTC, gburanov commented on libraries/cluster.rb
> +    def kafka_nodes
great! Thank you very much. This will be much better. WDYT about adding prefix "cluster_" to all these methods? We have quite many kafka nodes in all clusters for example and somebody could think that kafka_nodes will give him all the nodes in all clusters.

2019-01-21 16:31 UTC, asusac commented on libraries/cluster.rb
> +    def kafka_nodes
good point, will do

2019-01-21 16:55 UTC, gburanov approved these changes

2019-01-21 16:56 UTC, gburanov commented on libraries/cluster.rb
> +      "#{cluster_search("roles:dfc").first['fqdn']}:3121"
just one supoerminor comment - better use single brackets - thats what rubocop would said =)

2019-01-21 16:56 UTC, gburanov commented on libraries/cluster.rb
> +      "#{cluster_search("roles:dfc").first['fqdn']}:3121"
'roles:dfc'

2019-01-21 18:33 UTC, gburanov commented on libraries/cluster.rb
> +      "#{cluster_search("roles:dfc").first['fqdn']}:3121"
also - just random thought - maybe we can take random dfc (using sample) here. This is actually small change but it will split dfc load probably (not that we really need it but why not if we can)

2019-01-22 11:27 UTC, asusac commented on libraries/cluster.rb
> +      "#{cluster_search("roles:dfc").first['fqdn']}:3121"
👮 👍

2019-01-24 11:48 UTC, asusac commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor repetitive code in chef.new](https://trello.com/c/kJVdYKTn/2827-refactor-repetitive-code-in-chefnew)

2019-01-25 07:55 UTC, itszootime requested changes

2019-01-25 07:55 UTC, itszootime commented on libraries/cluster.rb
> +    def cluster_kafka_nodes
I don't think the naming here matches the return value of the method - I'd expect anything called `nodes` to return [`Chef::Node`](https://www.rubydoc.info/gems/chef/Chef/Node) objects. We could call them `kafka_connect`, `kafka_connect_value` or something similar?

Additionally, I'd add an optional `cluster` argument to this method which uses `node.cluster_name` as the default. This is useful for cases like indexer, where it needs to connect to Aerospike in a different cluster.

2019-03-04 18:49 UTC, asusac commented
moving base cookbook into chef.new as per https://trello.com/c/kJVdYKTn/3223-refactor-repetitive-cluster-search-code-in-chefnew, so closing this

2019-03-04 18:49 UTC, closed without merging